spring:
  application:
    name: simple-personality-test
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:~/personality-db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
server:
  servlet:
    context-path: /api/v1